### 넘파이 배열
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자
수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함.
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음.

### Numpy import
numpy 패키지를 사용하려면 먼저 패키지를 설치해야함.
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야함.
``` python
import numpy
import numpy as np
```

In [69]:
import numpy as np

### 1차원 배열 만들기
넘파이의 `array` 함수를 사용하여 리스트를 `ndarray` 타입으로 변경 가능

In [ ]:
ndarray_ = np.array([0,1,2,3,4])
ndarray_

In [ ]:
type(ndarray_)

In [ ]:
floats = np.array([1.0,2.0,3.0,4.0])
floats

In [ ]:
floats = np.array([0.1,0.2,0.3,0.4])
floats

파이썬 리스트와는 다르게 numpy 배열의 요소는 모두 같은 타입이어야 함.  
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름

In [ ]:
ndarray_ = np.array([1,1.5,2])
ndarray_

In [ ]:
ndarray_ = np.array(['문자열',1,1.5])
ndarray_

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원


In [ ]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 때
numbers = list(range(10))

result = []
for number in numbers:
    result.append(number*2)
result

In [ ]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2*numpy_numbers
result

In [ ]:
result = 2*numbers
result

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [ ]:
numbers1 = np.array([list(range(5))])
numbers2 = np.array([list(range(5,10))])

numbers1, numbers2

In [ ]:
result = (numbers1*5) + numbers2
result

In [ ]:
result = numbers1 == 3
result

In [ ]:
result = (numbers1 >2) & (numbers2 <10)
result

In [ ]:
numbers1>2, numbers2<10, result

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를<br>`array()`의 매개변수로 전달하면 2차원 배월을 생성할 수 있음

In [ ]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

In [ ]:
len(numpy_matrix)

In [ ]:
numpy_matrix[0]

In [ ]:
len(numpy_matrix[0])

### 3차원 배열 만들기
리스트의 요소로 2차원 형태를 띄는 리스트를 작성하면 3차원 배월로 만들 수 있음.

In [ ]:
three_d = [
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ], 
    [ 
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ],
    
]
numpy_three_d = np.array(three_d)
numpy_three_d

### 배열의 차원과 크기 구하기
`ndim` : 배열의 차원을 정수로 반환  
`shape` : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [ ]:
numpy_matrix.ndim, numpy_matrix.shape

In [ ]:
numpy_three_d.ndim, numpy_three_d.shape

### numpy 배열의 인덱싱
일반적으로 `배열변수[인데스]`의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게 `배열변수[인덱스, 인덱스,...]`의 형태로 사용함  
일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
numpy 2차원 배열 : `배열[인덱스, 인덱스]`

In [ ]:
three_d

In [ ]:
three_d[1][0][3]

In [ ]:
# numpy 3차원 배열
numpy_three_d

In [ ]:
numpy_three_d[1,0,3]

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]` 와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 `,`를 써야하는 것에 주의

In [ ]:
numpy_matrix

In [ ]:
numpy_matrix[:]

In [ ]:
numpy_matrix[:2]

In [ ]:
numpy_matrix[0,:2]

In [ ]:
numpy_matrix[:2,0]

In [ ]:
numpy_matrix[1:,1:]

In [ ]:
numpy_three_d[:1,:2,:2]

In [ ]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [ ]:
# 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

In [ ]:
# 이 행렬에서 값 14 을 인덱싱한다.
m[2,4] # m[-1,-1]

In [ ]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]

In [ ]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

In [ ]:
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,3:]

### 배열 인덱싱
**팬시 인덱싱(fancy indexing)** 이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱
`True`,`False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여  
새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [ ]:
numpy_array % 2

In [ ]:
numpy_array % 2 == 0

In [ ]:
numpy_array[numpy_array % 2 == 0]

### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된 배열을  
인덱스로 전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [ ]:
numpy_array

In [ ]:
index_array = np.array([0,2,3])

In [ ]:
numpy_array[index_array]

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  
  
인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우  
예외가 발생함

In [ ]:
index_array = np.array([0,2,20])

In [ ]:
numpy_array[index_array]

### 다차원 배열에서 배열 인덱싱

In [ ]:
numpy_matrix

In [ ]:
index_array = np.array([True,False,True])
numpy_matrix[:2,index_array]

In [ ]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경됨.
numpy_matrix[[2,1,0],:]

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 이 배열에서 3의 배수를 찾아라.
x[(x % 3 == 0)]

In [ ]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[((x % 4 == 1) & (x > 4))]

In [ ]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[((x % 3 == 0) & (x % 4 == 1))]

### numpy 배열의 자료형
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음
nump 배열의 데이터 타입을 확인하고자 한다면 `dtype` 속성으로 확인이 가능

In [ ]:
numpy_array = np.array([1,2,3])
numpy_array.dtype

In [ ]:
numpy_array = np.array([1.0,2,3])
numpy_array.dtype

In [ ]:
numpy_array = np.array(['1.0','2','3.0'])
numpy_array.dtype

`array()` 함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면  
자동으로 데이터 타입을 추론하여 지정하게 됨  
만약 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로  
데이터 타입을 지정해주면 됨

##### dtype의 접두사
b: 불리언, i: 정수, f: 실수, u: 유니코드

In [ ]:
numpy_array = np.array(['1.0','2','3.0'],dtype='f')
numpy_array.dtype

### numpy에서 Inf와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `Inf`, -1을 0으로 나누면 `-Inf`, 0을 0으로 나누면 `NaN`이 반환됨.

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`, `logspace`

### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [ ]:
numpy_array = np.zeros(5)
numpy_array

In [ ]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2, 3))
numpy_array

In [ ]:
# dtype 을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2, 3), dtype='i')
numpy_array

만약, dtype으로 문자열(U)로 지정하게 되었을 때, 문자열의 길이가 초과하면 초과된 부분이 손실됨.

### ones
크기가 정해져있고 원소를 1로 초기화한 배열을 생성하는 함수
`zeros` 함수와 사용법이 동일

In [ ]:
ones_array = np.ones((3,2,2),dtype='i')
ones_array

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본떠서 0 또는 1로 채워진 배열을 생성하는 함수 

In [ ]:
zeors_array = np.zeros_like(ones_array,dtype='f')
zeors_array

### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터' 로 채워진 배열을 생성
`zeros`, `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [ ]:
empty_array = np.empty((10,10))
empty_array

### arange
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [ ]:
arange_array = np.arange(10)
arange_array

In [ ]:
arange_array = np.arange(10,50)
arange_array

In [ ]:
arange_array = np.arange(50,10,-1)
arange_array

### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법, 배열의 `T` 속성으로 반환 받을 수 있음.

In [ ]:
numpy_matrix

In [ ]:
numpy_matrix.T

In [ ]:
numpy_three_d

In [ ]:
numpy_three_d.T # 2,3,4 -> 4,3,2

### 배열의 크기 변경
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태를 변경하려 한다면  
`reshape` 메서드를 사용하여 변경할 수 있음.

In [ ]:
numpy_array = np.zeros(12)
numpy_array

In [ ]:
reshape_array = numpy_array.reshape(4,3)
reshape_array

In [ ]:
reshape_array = numpy_array.reshape(2,6)
reshape_array

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape` 메서드에  
하나의 인자로 -1을 넣게 되면 다른 인자들을 통해서 추론하여 지정한다.

In [ ]:
reshape_array = numpy_array.reshape(6,-1)
reshape_array

In [ ]:
reshape_array = numpy_array.reshape(3,1,-1)
reshape_array

만약, `reshape` 메서드 인자들의 곱의 결과가 기존 배열 원소의 총합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 업는 경우엔 에러가 발생

In [ ]:
reshape_array = numpy_array.reshape(5,2)
reshape_array

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel` 메서드를 사용

In [ ]:
numpy_matrix = np.empty((3,4))
numpy_matrix

In [ ]:
numpy_array = numpy_matrix.flatten()
numpy_array

In [ ]:
numpy_array = numpy_matrix.ravel()
numpy_array

배열 사용에서 주의할 점은 *길이가 5인 1차원 배열*과 *5x1인 2차원 배열*,*1x5인 2차원 배열*은 서로 각각 다른 배열  
(요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다른 배열)

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis` 속성으로 차원을 증가시킬 수 있음.

In [ ]:
numpy_array

In [ ]:
newaxis_array = numpy_array[np.newaxis]
newaxis_array

### 배열 연결하기
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법  
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결  
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결
- `stack` :  `dstack` 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결.  
             (단, 연결 축을 개발자가 직접 지정)
- `r_` : 배열의 요소를 연결, 메서드인자를 `[]`에 전달함.
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결
- `tile` : 하나의 배열을 여러번 반복하여 연결

In [ ]:
zeros_array = np.zeros((3,4))
zeros_array

In [ ]:
ones_array = np.ones((3,2))
ones_array

In [ ]:
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array

In [ ]:
zeros_array = np.zeros((3,4))
zeros_array

In [ ]:
ones_array = np.ones((2,4))
ones_array

In [ ]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

In [ ]:
zeros_array = np.zeros((3,3))
zeros_array

In [ ]:
ones_array = np.ones((3,3))
ones_array

In [ ]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

In [ ]:
stack_array = np.stack([zeros_array, ones_array])
stack_array

In [ ]:
r_array = np.r_[zeros_array, ones_array]
r_array

In [ ]:
c_array = np.c_[zeros_array, ones_array]
c_array

In [ ]:
tile_array = np.tile(zeros_array,2)
tile_array

In [ ]:
tile_array = np.tile(zeros_array,(3,2))
tile_array

In [ ]:
zero_array = np.zeros((3,3))
one_array = np.ones((3,2))
hstack_array = np.hstack([zero_array, one_array])

In [ ]:
arange_array = np.arange(10, 160, 10)
reshape_array = arange_array.reshape(3,5)

vstack1_array = np.vstack([hstack_array,reshape_array])

In [ ]:
tile_array = np.tile(vstack1_array,(2,1))
tile_array

### 2차원 그리드 포인트 생성
좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로  
사각형의 영역을 나타내는 조합을 생성

In [ ]:
x = np.arange(3)
x

In [ ]:
y = np.arange(5)
y

In [ ]:
X, Y = np.meshgrid(x, y)

In [ ]:
[list(zip(x,y)) for x, y in zip(X,Y)]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음.

In [ ]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [ ]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
    z[index] = x[index] + y[index]



In [ ]:
%%time
z=x+y

In [ ]:
x = np.arange(5)
y = np.arange(10, 15)
z = np.arange(5)

In [ ]:
np.all(x == z)

In [ ]:
x

In [ ]:
x * 10

In [ ]:
10 ** x

### 브로드캐스팅
차원이 서로 다른 배열을 연사하는 기능, 부족한 차원에 대하여 반복 확장하여  
큰 배열의 크기에 맞춘 후 연산을 진행

In [ ]:
x = np.arange(5)
x

In [ ]:
x+1

In [ ]:
x = np.arange(15)
x = x.reshape(3,5)
x

In [ ]:
y = np.arange(5)
y

In [ ]:
x + y

In [ ]:
y = np.arange(3)
y = y.reshape(3,1)
y

In [ ]:
x+y

### 차원 축소 연산
배열의 하나의 행을 하나의 집합으로 보고 그 집합에 대한 집계 처리 결과로  
새로운 값을 반환하여 배열을 생성

In [ ]:
x = np.arange(10)
x = x.reshape(2,5)
x

In [ ]:
x.max()

In [ ]:
x.min()

In [ ]:
x.mean()

In [ ]:
x.sum(axis=1)

### 정렬
- `sort` 메서드로 배열을 정렬 할 수 있음  
- `axis` 매개변수로 정렬 기준을 정할 수 있음  
- `axis=0`: 행을 따로 분리하여 정렬  
- `axis=1`: 열을 따로 분리하여 정렬  
`axis`를 지정하지 않으면 가장 나중 차원을 기준으로 정렬

In [ ]:
x = np.array(
    [[5,2,7,4],
    [11,8,6,5],
    [8,5,11,2]]
)
x

In [ ]:
x.sort()
x

In [ ]:
x.sort(axis=0)
x

In [ ]:
x.sort(axis=1)
x

In [ ]:
np.argsort(x)

In [ ]:
[5,11,12],
[0,18,22],
[8,2,7]

x = np.array(
    [[5,11,12],
    [0,18,22],
    [8,2,7]
])
x

In [ ]:
x.max()

In [ ]:
x.sum(axis=1)

In [ ]:
x.max(axis=1)

In [ ]:
x.mean(axis=0)

In [ ]:
x.min(axis=0)

### Numpy 배열 통계 연산
- 데이터 개수 구하기 : `len()` 내장 함수
- 표본 평균 : `mean` 메서드
- 표본 분산 : `var()` 메서드
- 표본 표준편차 : `std()` 메서드
- 최대, 최소 : `max()`, `min()` 메서드
- 중앙값 : `median()` 메서드
- 사분위수 : `percentile()` 메서드

In [ ]:
samples = np.array([9,2,4,20,24,2,23,92,24,-23])
samples

In [ ]:
sample_volume = len(samples)
sample_volume

In [ ]:
sample_mean = samples.mean()
sample_mean

In [ ]:
sample_mean = np.mean(samples)
sample_mean

In [ ]:
sample_variance = samples.var()
sample_variance

In [ ]:
sample_variance = np.var(samples)
sample_variance

In [17]:
sample_standard = samples.std()
sample_standard

28.365648238670662

In [21]:
sample_standard = np.std(samples)
sample_standard

28.365648238670662

In [23]:
samples_max = samples.max()
samples_max

92

In [25]:
samples_min = samples.min()
samples_min

-23

In [29]:
samples_median = np.median(samples)
samples_median

14.5

In [32]:
sample_0per = np.percentile(samples,0)
sample_0per

-23.0

In [34]:
sample_25per = np.percentile(samples,25)
sample_25per

2.5

In [36]:
sample_50per = np.percentile(samples,50)
sample_50per

14.5

In [38]:
sample_75per = np.percentile(samples,75)
sample_75per

23.75

In [39]:
sample_100per = np.percentile(samples,100)
sample_100per

92.0

### 난수 생성에 필요한 시드 설정
numpy 패키지에 있는 `seed()` 메서드에 매개변수로 난수 생성 시 필요한 시드를 설정함.

In [66]:
np.random.seed(10)

In [49]:
random_array = np.random.rand(10)
random_array

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

### 데이터 순서 임의로 바꾸기
numpy 패키지의 random 하위 패키지의 `shuffle()` 메서드로 배열을 임의 순서로 변경 가능(자체 변환)

In [67]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.random.shuffle(range_array)
range_array

array([8, 2, 5, 6, 3, 1, 0, 7, 4, 9])

### 데이터 샘플링
모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는 방법  
numpy 패키지의 random 하위패키지의 `choice(모집단배열, 표본크기, 중복선택여부,  
 각 요소의 선택확률)` 메서드로 사용가능

In [70]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
probability_array = [0.1,0.05,0.05,0,0.15,0.25,0.1,0.05,0.05,0.2]
sample_array = np.random.choice(population_array, 10000, p=probability_array)
sample_array

array([5, 1, 7, ..., 4, 6, 5])

### 난수 배열 생성
- `rand()` : 0과 1 사이의 균일 분포를 따르는 난수 배열 생성
- `randn()` : 표준 정규 분포를 따르는 난수 배열 생성
- `randint(low, high=정수, size=정수 혹은 튜플)` : 지정한 범위 정수의 균일분포를 따르는 난수 배열 생성

In [82]:
rand_array = np.random.rand(10)
rand_array


array([0.87740478, 0.38559555, 0.52463761, 0.31002708, 0.06428103,
       0.29177199, 0.07001156, 0.36607868, 0.43857591, 0.89077166])

In [84]:
randn_array = np.random.randn(10)
randn_array

array([-0.02841818,  0.40587482,  0.56902841, -0.99170997, -0.11761782,
        0.77991959, -1.12338202, -0.03925393,  1.37842968,  0.0636804 ])

In [87]:
randomint_array = np.random.randint(10)
randomint_array

5

In [91]:
randomint_array = np.random.randint(10,high=20,size=10)
randomint_array

array([14, 14, 16, 17, 18, 11, 13, 18, 17, 12])

In [93]:
randomint_array = np.random.randint(10,high=20,size=(3,5))
randomint_array

array([[18, 14, 17, 15, 15],
       [19, 10, 12, 19, 17],
       [17, 15, 16, 17, 15]])

### 정수 데이터 카운팅
배열의 요소가 정수이면 `unique()` 메서드나 `bincount()` 메서드로 간단하게 분석할 수 있음

In [97]:
analysis_array = np.unique(sample_array)
analysis_array

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [99]:
analysis_array = np.unique(sample_array,return_counts=True)
analysis_array

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([1000,  481,  457, 1565, 2520,  992,  475,  478, 2032], dtype=int64))

In [100]:
analysis_array = np.bincount(sample_array,minlength=10)
analysis_array

array([1000,  481,  457,    0, 1565, 2520,  992,  475,  478, 2032],
      dtype=int64)

In [117]:
coin_array = np.random.randint(0,high=2,size=10)
coin_array

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [151]:
dice_array = np.random.randint(1,high=7,size=100)
dice_array = np.mean(dice_array)
dice_array

3.56

In [ ]:
price = 10000
price_array = np.random.randn(250)
for price in price_array(250):
    price = price-(price*price_array)
    print(price)

In [174]:
price = 10000
variation_ranges = (np.random.randn(250)/100)+1
stock_prices = []

for ratio in variation_ranges:
    price = round(price * round(ratio,4))
    stock_prices.append(price)

stock_prices_array = np.array(stock_prices)
stock_prices_array

array([10055, 10034, 10163, 10284, 10276, 10366, 10421, 10424, 10484,
       10513, 10713, 10738, 10693, 10683, 10795, 10742, 10843, 10778,
       10804, 10886, 10975, 10906, 10749, 10672, 10540, 10547, 10635,
       10750, 10747, 10694, 10706, 10843, 11015, 11014, 11002, 10829,
       10887, 11067, 11040, 10997, 11037, 11081, 11114, 10960, 10963,
       10892, 11047, 11125, 11136, 11156, 11168, 11195, 11215, 11431,
       11278, 11226, 11193, 11101, 11009, 10896, 11068, 11129, 11064,
       11051, 10990, 10906, 10920, 10837, 11013, 10944, 11022, 10836,
       10698, 10783, 10765, 10583, 10644, 10604, 10717, 10692, 10829,
       10720, 10566, 10464, 10597, 10614, 10636, 10669, 10476, 10624,
       10540, 10418, 10420, 10257, 10506, 10553, 10517, 10401, 10448,
       10361, 10527, 10490, 10652, 10632, 10588, 10752, 10883, 10725,
       10686, 10755, 10593, 10663, 10801, 10771, 10980, 11087, 11035,
       11092, 10948, 10820, 10775, 10864, 10787, 10804, 10737, 10646,
       10525, 10441,